version: "3.3"

networks:
  web:
    external: true

services:
  node_exporter:
    image: ${NODE_EXPORTER_IMAGE:-prom/node-exporter}:${NODE_EXPORTER_VERSION:-latest}
    restart: unless-stopped
    hostname: ${NODE_EXPORTER_HOSTNAME}

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

    expose:
      - 9100

    ports:
      - ${NODE_EXPORTER_PORT:-9100}:9100

    networks:
      - web
